/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefsRouteImport } from './routes/briefs'
import { Route as EventAnalysisRouteImport } from './routes/event-analysis'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as PatternsRouteImport } from './routes/patterns'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefsRoute = BriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => rootRouteImport,
} as any)
const EventAnalysisRoute = EventAnalysisRouteImport.update({
  id: '/event-analysis',
  path: '/event-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefs': typeof BriefsRoute
  '/event-analysis': typeof EventAnalysisRoute
  '/incidents': typeof IncidentsRoute
  '/patterns': typeof PatternsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefs': typeof BriefsRoute
  '/event-analysis': typeof EventAnalysisRoute
  '/incidents': typeof IncidentsRoute
  '/patterns': typeof PatternsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefs': typeof BriefsRoute
  '/event-analysis': typeof EventAnalysisRoute
  '/incidents': typeof IncidentsRoute
  '/patterns': typeof PatternsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/briefs' | '/event-analysis' | '/incidents' | '/patterns'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/briefs' | '/event-analysis' | '/incidents' | '/patterns'
  id:
    | '__root__'
    | '/'
    | '/briefs'
    | '/event-analysis'
    | '/incidents'
    | '/patterns'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefsRoute: typeof BriefsRoute
  EventAnalysisRoute: typeof EventAnalysisRoute
  IncidentsRoute: typeof IncidentsRoute
  PatternsRoute: typeof PatternsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs': {
      id: '/briefs'
      path: '/briefs'
      fullPath: '/briefs'
      preLoaderRoute: typeof BriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-analysis': {
      id: '/event-analysis'
      path: '/event-analysis'
      fullPath: '/event-analysis'
      preLoaderRoute: typeof EventAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefsRoute: BriefsRoute,
  EventAnalysisRoute: EventAnalysisRoute,
  IncidentsRoute: IncidentsRoute,
  PatternsRoute: PatternsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
