"""initial postgresql schema

Revision ID: 5e0dac902f87
Revises:
Create Date: 2026-07-18 12:43:01.957192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5e0dac902f87"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brief_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("celery_task_id", sa.String(length=64), nullable=True),
        sa.Column(
            "report_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "brief_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("top_causal_signature", sa.String(length=255), nullable=True),
        sa.Column("most_representative_report_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_brief_jobs_celery_task_id"),
        "brief_jobs",
        ["celery_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_brief_jobs_status"), "brief_jobs", ["status"], unique=False
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_filename", sa.String(length=512), nullable=True),
        sa.Column("source_file_path", sa.String(length=1024), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("incident_title", sa.Text(), nullable=True),
        sa.Column("incident_type", sa.String(length=255), nullable=True),
        sa.Column("incident_date", sa.Date(), nullable=True),
        sa.Column("location", sa.String(length=512), nullable=True),
        sa.Column("operation_type", sa.String(length=255), nullable=True),
        sa.Column("vessel_type", sa.String(length=255), nullable=True),
        sa.Column("casual_signature", sa.String(length=255), nullable=True),
        sa.Column(
            "vessel_information", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "weather_conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "environmental_factors",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("pollution", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "property_damage", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "equipment_involved", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "sequence_of_events", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "immediate_causes", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "root_causes", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "contributing_factors",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "human_factors", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "technical_failures", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "regulatory_issues", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "lessons_learned", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "corrective_actions", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "safety_recommendations",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("keywords", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("injuries", sa.Integer(), nullable=True),
        sa.Column("fatalities", sa.Integer(), nullable=True),
        sa.Column("overall_confidence", sa.Float(), nullable=True),
        sa.Column("human_review_required", sa.Boolean(), nullable=False),
        sa.Column(
            "fields_requiring_review",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("full_text", sa.Text(), nullable=True),
        sa.Column("vector_indexed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reports_casual_signature"),
        "reports",
        ["casual_signature"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reports_content_hash"), "reports", ["content_hash"], unique=True
    )
    op.create_index(
        op.f("ix_reports_fatalities"), "reports", ["fatalities"], unique=False
    )
    op.create_index(
        op.f("ix_reports_human_review_required"),
        "reports",
        ["human_review_required"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reports_incident_date"), "reports", ["incident_date"], unique=False
    )
    op.create_index(
        op.f("ix_reports_incident_type"), "reports", ["incident_type"], unique=False
    )
    op.create_index(
        op.f("ix_reports_ingested_at"), "reports", ["ingested_at"], unique=False
    )
    op.create_index(op.f("ix_reports_injuries"), "reports", ["injuries"], unique=False)
    op.create_index(op.f("ix_reports_location"), "reports", ["location"], unique=False)
    op.create_index(
        op.f("ix_reports_operation_type"), "reports", ["operation_type"], unique=False
    )
    op.create_index(
        "ix_reports_operation_vessel",
        "reports",
        ["operation_type", "vessel_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reports_overall_confidence"),
        "reports",
        ["overall_confidence"],
        unique=False,
    )
    op.create_index(
        "ix_reports_review_confidence",
        "reports",
        ["human_review_required", "overall_confidence"],
        unique=False,
    )
    op.create_index(
        "ix_reports_type_location",
        "reports",
        ["incident_type", "location"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reports_vector_indexed"), "reports", ["vector_indexed"], unique=False
    )
    op.create_index(
        op.f("ix_reports_vessel_type"), "reports", ["vessel_type"], unique=False
    )
    op.create_table(
        "field_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=128), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=True),
        sa.Column("human_revision_status", sa.String(length=32), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column(
            "supporting_quotes", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "source_page_numbers",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "report_id", "field_name", name="uq_fieldmeta_report_field"
        ),
    )
    op.create_index(
        op.f("ix_field_metadata_confidence"),
        "field_metadata",
        ["confidence"],
        unique=False,
    )
    op.create_index(
        op.f("ix_field_metadata_field_name"),
        "field_metadata",
        ["field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_field_metadata_human_revision_status"),
        "field_metadata",
        ["human_revision_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_field_metadata_report_id"),
        "field_metadata",
        ["report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_field_metadata_status"), "field_metadata", ["status"], unique=False
    )
    op.create_table(
        "ingestion_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("celery_task_id", sa.String(length=64), nullable=True),
        sa.Column("filename", sa.String(length=512), nullable=True),
        sa.Column("content_type", sa.String(length=128), nullable=True),
        sa.Column("source_file_path", sa.String(length=1024), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("parsed_text", sa.Text(), nullable=True),
        sa.Column("report_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingestion_jobs_celery_task_id"),
        "ingestion_jobs",
        ["celery_task_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_jobs_report_id"),
        "ingestion_jobs",
        ["report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ingestion_jobs_status"), "ingestion_jobs", ["status"], unique=False
    )
    op.create_table(
        "vocabulary_terms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=64), nullable=False),
        sa.Column("term", sa.String(length=255), nullable=False),
        sa.Column("normalized_term", sa.String(length=255), nullable=False),
        sa.Column("first_seen_report_id", sa.Integer(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_report_id"], ["reports.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "field_name", "normalized_term", name="uq_vocab_field_term"
        ),
    )
    op.create_index(
        op.f("ix_vocabulary_terms_field_name"),
        "vocabulary_terms",
        ["field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vocabulary_terms_normalized_term"),
        "vocabulary_terms",
        ["normalized_term"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_vocabulary_terms_normalized_term"), table_name="vocabulary_terms"
    )
    op.drop_index(op.f("ix_vocabulary_terms_field_name"), table_name="vocabulary_terms")
    op.drop_table("vocabulary_terms")
    op.drop_index(op.f("ix_ingestion_jobs_status"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_report_id"), table_name="ingestion_jobs")
    op.drop_index(op.f("ix_ingestion_jobs_celery_task_id"), table_name="ingestion_jobs")
    op.drop_table("ingestion_jobs")
    op.drop_index(op.f("ix_field_metadata_status"), table_name="field_metadata")
    op.drop_index(op.f("ix_field_metadata_report_id"), table_name="field_metadata")
    op.drop_index(
        op.f("ix_field_metadata_human_revision_status"), table_name="field_metadata"
    )
    op.drop_index(op.f("ix_field_metadata_field_name"), table_name="field_metadata")
    op.drop_index(op.f("ix_field_metadata_confidence"), table_name="field_metadata")
    op.drop_table("field_metadata")
    op.drop_index(op.f("ix_reports_vessel_type"), table_name="reports")
    op.drop_index(op.f("ix_reports_vector_indexed"), table_name="reports")
    op.drop_index("ix_reports_type_location", table_name="reports")
    op.drop_index("ix_reports_review_confidence", table_name="reports")
    op.drop_index(op.f("ix_reports_overall_confidence"), table_name="reports")
    op.drop_index("ix_reports_operation_vessel", table_name="reports")
    op.drop_index(op.f("ix_reports_operation_type"), table_name="reports")
    op.drop_index(op.f("ix_reports_location"), table_name="reports")
    op.drop_index(op.f("ix_reports_injuries"), table_name="reports")
    op.drop_index(op.f("ix_reports_ingested_at"), table_name="reports")
    op.drop_index(op.f("ix_reports_incident_type"), table_name="reports")
    op.drop_index(op.f("ix_reports_incident_date"), table_name="reports")
    op.drop_index(op.f("ix_reports_human_review_required"), table_name="reports")
    op.drop_index(op.f("ix_reports_fatalities"), table_name="reports")
    op.drop_index(op.f("ix_reports_content_hash"), table_name="reports")
    op.drop_index(op.f("ix_reports_casual_signature"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_brief_jobs_status"), table_name="brief_jobs")
    op.drop_index(op.f("ix_brief_jobs_celery_task_id"), table_name="brief_jobs")
    op.drop_table("brief_jobs")
    # ### end Alembic commands ###
