"""add event_analysis_jobs table

Revision ID: 605851bb36cb
Revises: 5e0dac902f87
Create Date: 2026-07-20 17:56:30.014050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '605851bb36cb'
down_revision: Union[str, Sequence[str], None] = '5e0dac902f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_analysis_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('operation_type', sa.String(length=255), nullable=True),
    sa.Column('vessel_type', sa.String(length=255), nullable=True),
    sa.Column('event_summary', sa.Text(), nullable=True),
    sa.Column('severity_stage', sa.String(length=32), nullable=True),
    sa.Column('near_miss_count', sa.Integer(), nullable=True),
    sa.Column('serious_count', sa.Integer(), nullable=True),
    sa.Column('fatal_count', sa.Integer(), nullable=True),
    sa.Column('near_miss_report_ids', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('serious_report_ids', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('fatal_report_ids', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_payload', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_analysis_jobs_celery_task_id'), 'event_analysis_jobs', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_event_analysis_jobs_status'), 'event_analysis_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_analysis_jobs_status'), table_name='event_analysis_jobs')
    op.drop_index(op.f('ix_event_analysis_jobs_celery_task_id'), table_name='event_analysis_jobs')
    op.drop_table('event_analysis_jobs')
    # ### end Alembic commands ###
